apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:1.4
          ports:
            - protocol: UDP
              containerPort: 514

---

apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
spec:
  type: NodePort
  selector:
    app: fluent-bit
  ports:
    - protocol: UDP
      port: 514
      targetPort: 514

