apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:7.6.2
          ports:
            - protocol: UDP
              containerPort: 514
          volumeMounts:
            - name: input-syslog
              mountPath: /usr/share/logstash/pipeline/input_syslog.conf
              readOnly: true
      volumes:
        - name: input-syslog
          configMap:
            name: logstash-input-syslog

---

apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
    - protocol: UDP
      port: 514
      targetPort: 514

